import './globals.css'
import { Oswald } from 'next/font/google'
import type { Metadata } from 'next'
import type { Children } from '§/types'

const osw = Oswald({ subsets: ['latin'] })

export const metadata: Metadata = { 
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Children) {
  return (
    <html lang="en">
      <body className={osw.className}>
        <main>{children}</main>
      </body>
    </html>
  )
}
